spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql


  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: validate
      #ddl-auto: create-drop

    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: ERROR