spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql


  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: create
      generate_statistics: true

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  shell:
    interactive:
      enabled: false

logging:
  level:
    #    ROOT: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE